### ISSUE TITLE
[Issue] Generate button's progress is wrong

### ISSUE THREAD

**Issue by AznamirWoW** [BinaryQuantumSoul/sdnext-modernui#76] opened 2024-06-28 11:48 UTC
### Issue Description

'Generate' button progress seems to go 2x the actual rate, shows 100% while the generation is only at 25/50 steps for a single image. For batches and X/Y/Z scripts the completion shows 100% after just the first image generated and stays like that until the whole process finishes.

### Backend

Firefox

### Branch

Desktop

### Version Platform Description

Version: app=sd.next updated=2024-06-28 hash=6fb7cee8 branch=dev

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment] 2024-06-28 13:13
which workflow? standard txt2img? any thing added to workflow (such as face-hires, adetailer, etc.)?
which ui? standard or modernui?

i cannot reproduce using standard txt2img and standard ui.

**Comment by AznamirWoW** [comment] 2024-06-28 13:51
> which workflow? standard txt2img? any thing added to workflow (such as face-hires, adetailer, etc.)? which ui? standard or modernui?
> 
> i cannot reproduce using standard txt2img and standard ui.

Modern UI, text to image. Started around master to dev merge a few days ago.

![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/101997116/6740865d-315b-4eba-b37f-12ec0714fc1e)

**Comment by AznamirWoW** [comment] 2024-06-28 13:57
Also happens with standard UI
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/101997116/c09557a6-a8ac-42a6-aca9-d43cb708306b)

**Comment by AznamirWoW** [comment] 2024-06-28 14:01
@vladmandic looks like it happens with 'DPM SDE' sampler, but not with 'Euler a' or some others.

**Comment by vladmandic** [comment] 2024-06-28 14:30
right - that helps a lot! 
issue is that some samplers have internal number of steps higher if they are samplers of higher order - such as DPM SDE.
i've included that in step calculation - fixed in dev branch.

**Comment by AznamirWoW** [comment] 2024-06-30 03:17
@vladmandic after this fix img2img progress % is going half the actual rate, both DPM SDE and Euler a samplers.

**Comment by vladmandic** [comment] 2024-06-30 15:10
fixed (again), hope its ok this time.

**Closed by vladmandic** 2024-06-30 15:10 UTC
Labels: question
